apiVersion: v1
kind: Service
metadata:
  name: {{ include "chartapigw.fullname" . }}
  labels:
    {{- include "chartapigw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  {{ if eq .Values.service.tpe "NodePort" }}
      nodePort: {{ .values.service.port }}
  {{ end }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chartapigw.selectorLabels" . | nindent 4 }}
