apiVersion: v1
kind: Service
metadata:
  name: {{ include "chartgo.fullname" . }}
  labels:
    {{- include "chartgo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  {{ if eq .Values.service.tpe "NodePort" }}
      nodePort: {{ .values.service.port }}
  {{ end }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chartgo.selectorLabels" . | nindent 4 }}
